---

environment_type: testing

########################
# mysql
mysql_root_username: root
mysql_root_password: root
mysql_local_installation: true
mysql_login_host: localhost

attach_mounts: true
drupal_reverse_proxies_ips: 172.31.47.14
fqdn_suffix: louisianadigitallibrary.org

php_upload_max_filesize: 12G
php_post_max_size: 12G