---
# install ffmpeg

- name: add the ffmpeg ppa for trusty
  apt_repository: repo="ppa:mc3man/trusty-media"

- name: apt-get update
  apt: update_cache=yes cache_valid_time=86400

- name: Dist upgrade
  apt: upgrade=dist cache_valid_time=86400

- name: Install ffmpeg
  apt: name=ffmpeg