---
- name: Install islandora server side utilities
  apt: 
    name: "{{item}}"
  with_items:
    - imagemagick
    - lame
    - poppler-utils
    - bibutils

- include: tesseract.yml
- include: ffmpeg.yml
- include: fits.yml
