---
- hosts: all
  become: yes
  roles: 
    - ansible-role-islandora-build-prep
    - java8
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
  tasks:
    - name: Install apache-php
      apt:
        name: libapache2-mod-php5
