---
- hosts: all
  become: yes
  roles:
    - ansible-role-islandora-build-prep
    # - ansible-role-java
    - ansible-role-git
    - ansible-role-apache
    - ansible-role-php
    - ansible-role-php-mysql
    - ansible-role-composer
    - ansible-role-drush
  tasks:
    - name: Install apache-php
      apt:
        name: libapache2-mod-php

    - name: Install mysql-client when needed
      apt:
        name: mysql-client
      when: not mysql_local_installation
