---
- hosts: all
  become: yes
  tasks:
    - name: Ensure Drupal link target exists
      file:
        state: directory
        path: "{{ drupal_home_link_target }}"

    - name: Ensure Drupal symlink exists
      file:
        path: "{{ drupal_core_path }}"
        state: link
        src: "{{ drupal_home_link_target }}"


    - name: Check out Drupal Core to the default location.
      git:
        repo: "{{ drupal_repo_url }}"
        version: "{{ drupal_core_version }}"
        update: "{{ drupal_keep_updated }}"
        dest: "{{ drupal_core_path }}"



    # TODO - since this uses mysql root creds to create dbs if needed
    #        don't create them in databases.yml
    - name: Install Drupal for all sites.
      command: >
        drush si {{ drupal_install_profile }} -y
        --site-name="{{ item }}"
        --account-name={{ drupal_admin_name }}
        --account-pass={{ drupal_admin_password }}
        --db-url=mysql://{{ item }}:{{ item }}@{{ mysql_login_host }}/{{ item }}
        --db-su={{ mysql_login_user }}
        --db-su-pw={{ mysql_login_password }}
        --sites-subdir={{ item }}
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/sites/{{ item }}/settings.php
      with_items: "{{ institutions }}"

    - name: Remove default site
      file:
        path: "{{ drupal_core_path }}/sites/default"
        state: absent

    - name: Set default site symlink
      file:
        path: "{{ drupal_core_path }}/sites/default"
        src: "{{ drupal_core_path }}/sites/ldl"
        state: link

    # SEE: https://drupal.org/node/2121849#comment-8413637
    - name: Set permissions properly on settings.php.
      file:
        path: "{{ drupal_core_path }}/sites/{{ item }}/settings.php"
        mode: 0744
      with_items: "{{ institutions }}"

    - name: Set permissions properly on files directory.
      file:
        path: "{{ drupal_core_path }}/sites/{{ item }}/files"
        mode: 0755
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      with_items: "{{ institutions }}"
