---
- hosts: all
  become: yes
  tasks:
    - name: Ensure Drupal link target exists
      file:
        state: directory
        path: "{{ drupal_home_link_target }}"

    - name: Ensure Drupal symlink exists
      file:
        path: "{{ drupal_core_path }}"
        state: link
        src: "{{ drupal_home_link_target }}"


    - name: Check out Drupal Core to the default location.
      command: "drush -y dl drupal-7.x --drupal-project-rename=ldl --destination={{ drupal_volume_mount_point }}"

    - name: Drush site install.
      command: drush site-install -y standard --db-url='mysql://ldl:ldl@localhost/ldl' --site-name='Louisiana Digital Library'
      args:
        chdir: "{{ drupal_core_path }}"

    # SEE: https://drupal.org/node/2121849#comment-8413637
    - name: Set permissions properly on settings.php.
      file:
        path: "{{ drupal_core_path }}/sites/default/settings.php"
        mode: 0644
      with_items: "{{ institutions }}"

    - name: Set permissions on files directory.
      file:
        path: "{{ drupal_core_path }}/sites/{{ item }}/files"
        mode: 0755
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      with_items: "{{ institutions }}"
