---
#- include: vagrant-hack.yml
- include: pre-up.yml
- include: build.yml
- include: v1.2.2.5.yml
- include: LDL-0.5.x.yml
- include: LDL-0.6.x.yml
- include: collections.yml
- include: post-up.yml
