---
- hosts: all
  become: yes
  tasks:
  - name: Set filesystem permissions wide-open for ease of dev.
    file:
      path: "{{ drupal_home_link_target }}"
      mode: 0777
      recurse: yes
      follow: yes
    when: environment_type == 'dev'

  - name: Reset Drupal permissions.
    command: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
    when: environment_type != 'dev'

  # mik stuff
  - name: Get mik.
    git:
      version: 3613a3d5ae49a6828d278a4171ce4b2575fa7e4a
      repo: https://github.com/MarcusBarnes/mik/
      dest: "/opt/mik"
      force: yes
    register: git_deploy
    until: git_deploy|succeeded


  - name: composer install mik
    command: composer install
    args:
      chdir: /opt/mik

  - name: copy sample files
    unarchive:
      src: migrations/files/mik-poc.zip
      dest: /tmp/

  - debug:
      msg: Run `php mik --config /tmp/mik-poc/config.ini` to test mik.
