---
- hosts: all
  become: yes
  tasks:
  - name: Set filesystem permissions wide-open for ease of dev.
    file:
      path: "{{ drupal_home_link_target }}"
      mode: 0777
      recurse: yes
      follow: yes
    when: environment_type == 'dev'

  - name: Reset Drupal permissions.
    command: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
    when: environment_type != 'dev'
